title: 'Alt Password Protect Settings'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: hide_password_protected_entries_from_listings
            field:
              default: true
              type: toggle
              display: 'Hide password protected entries from listings?'
              icon: toggle
              listable: hidden
              instructions_position: above
              replicator_preview: true
              hide_display: false
